### ISSUE TITLE
A little question about the gating mechanism

### ISSUE THREAD

**Issue by 14H034160212** [nuric/deeplogic#11]
Hi,

I just have a little question for the final line `state = gate2([state, new_state, gate])`. I am wondering whether `new_state` here is `new_states`? Thanks.
![image](https://user-images.githubusercontent.com/23516191/107942716-80e11180-6ff0-11eb-8987-cb255d1eb2b6.png)

Happy Chinese New year,
Qiming

**Comment by 14H034160212** [comment]
But there is a error when I use `new_states` to replace `new_state`.
The error is located on line 176.
![image](https://user-images.githubusercontent.com/23516191/107946453-eb488080-6ff5-11eb-8505-43750bbc5fd9.png)
It is called `ValueError: Input 0 is incompatible with layer repeat_to_ctx: expected ndim=2, found ndim=3`.

**Comment by 14H034160212** [comment]
What I am doing is I fix the gate2 function as the following.
![image](https://user-images.githubusercontent.com/23516191/107946837-6f9b0380-6ff6-11eb-9862-2d8ee2bd8fc7.png)
And then I remove the `new_state` in order to keep the ndim as same as `repeat_toctx`.
The program can run now. 
My question is for gating mechanism, I see in the gate1, you use sigmoid and in the gate2 you design a new function `xyg[2]*xyg[0] + (1-xyg[2])*xyg[1]`. Can you explain a little bit to make it more clear? Thanks a lot!

**Comment by nuric** [comment]
Hello, it would be difficult to say without checking the older version. The state tensor might have different number of dimensions with would explain the error. I think what you did should work, just make sure to follow shape annotations at the end of the lines to correctly gate the right dimension. Hope that helps.

**Comment by 14H034160212** [comment]
This issue has been solved by that following issue.
https://github.com/nuric/deeplogic/issues/14
