### ISSUE TITLE
What kind of Attention has been used in the model?

### ISSUE THREAD

**Issue by 14H034160212** [nuric/deeplogic#13]
Hi, 

I am thinking about the code for Attention. I am wondering what kind of Attention has been used in the model? 
![image](https://user-images.githubusercontent.com/23516191/108801572-fbb2b980-75fa-11eb-8a7b-f3a4ed605105.png)
![image](https://user-images.githubusercontent.com/23516191/108801670-2bfa5800-75fb-11eb-9ab9-d47862a5a5e5.png)

For those screenshots, you defined the Attention dense function. Is it soft Attention or hard Attention, or you use dense to simulate the Attention here?

Thanks.

**Comment by nuric** [comment]
This is soft attention based on a learnable score obtained by `att_dense`. In this case, the sigmoid activation gives the score between 0 and 1 which corresponds to whether the rule is selected or not.
