### ISSUE TITLE
Some questions about the future work

### ISSUE THREAD

**Issue by 14H034160212** [nuric/deeplogic#6]
Hi,

Very good work! I guess this paper is the first one to consider attention to solve symbolic reasoning. It is exciting to me. Do you have any other related recommend papers or links? What is your plan for the project? Do you think it is possible to combine it with natural language? I think it might be possible to transfer the symbolic predicate to similar natural language cases like the facts, rules, and questions are both natural languages. This model might be used to do the forward chaining and backward chaining reasoning over the natural language. How do you think about it?

Cheers

**Comment by nuric** [comment]
Thank you for your comments and interest. There are many papers trying to incorporate symbolic logic and deep learning under the umbrella of neuro-symbolic systems, you can find many under the related work section of the paper. It would be difficult to answer your questions in Github issue but some future was mentioned in the conclusion section.

As for the natural language aspect, works such as [Neural Theorem Provers](https://arxiv.org/pdf/1705.11040.pdf) perform backward chaining on natural language embeddings of constants and predicates. Perhaps you can look at that direction which has many extensions works too.
