### ISSUE TITLE
An issue when I try to replace the predicate using natural language

### ISSUE THREAD

**Issue by 14H034160212** [nuric/deeplogic#7]
Hi,

Here is an issue I met when I replace the dataset using a natural language dataset which did the same thing but the format is natural language. The train and val files reading are all good, the issue is from the `  model.fit_generator(traind, epochs=ARGS.epochs,
                      callbacks=callbacks,
                      validation_data=vald,
                      verbose=1, shuffle=True,
                      initial_epoch=callbacks[0].get_last_epoch())`
I suspect it might be from the character level embedding. Cause from `train.py` I find in the `create_model` function, it seems like rely on the `CHAR_IDX`. Here is the code `model = build_model(MODEL_NAME, MODEL_WF,
                      char_size=len(CHAR_IDX)+1,
                      dim=ARGS.dim,
                      **kwargs)`

And here is the information of the bug.
![image](https://user-images.githubusercontent.com/23516191/90357024-a757db80-e0a5-11ea-9405-6760551d4976.png)

The format of the natural language is like that. It is actually a binary classification similar like the deeplogic synthetic dataset. 
`"context":"Anne is rough. Cold people are rough. If Anne is green then Anne is blue. Rough people are young. Anne is blue. If someone is rough and furry then they are blue. All young people are cold. If someone is rough and nice then they are green. Anne is young."`
`"question":"Anne is rough."`
`"label":1`

Cheers

**Comment by nuric** [comment]
Hello, you are probably on the right track , it does seem like the embedding layer. But because it is specific to your dataset, I wouldn't be able to help you debug these issues. [StackOverflow](https://stackoverflow.com/) might be better place to ask for help specific to your code.

**Comment by 14H034160212** [comment]
I fixed this issue by debugging the `def __getitem__` method from the `utils.py` file. And now I have transferred the model to the natural language senario.
