### ISSUE TITLE
A question about the Commented gating code

### ISSUE THREAD

**Issue by 14H034160212** [nuric/deeplogic#9]
Hi, 

Here is a question that I saw there are some codes have been commented in the `ima.py` which is about applying gating. Have you tried to run the program with those lines? I think it is a great idea to think about the gate structure in the model.

<img width="421" alt="commented_gate_structure" src="https://user-images.githubusercontent.com/23516191/90974706-a0d3d300-e581-11ea-9b1a-acde265c621a.png">

Kind regards

**Comment by nuric** [comment]
Hello, we have initially formulated the propagation of states using a gating mechanism. In the case the model was finished processing the logic program, it had an explicit way for just using the previous state. This was then integrated as the null rule which achieves a similar affect but that the model can attend to explicitly. But it's worth investigating further such as using a GRU cell entirely to update the state which incorporates a gating mechanism.

**Comment by 14H034160212** [comment]
Hi, I just have a little question for the final line `state = gate2([state, new_state, gate])`. I am wondering whether `new_state` here is `new_states`? Thanks.

Cheers,
Qiming

**Comment by 14H034160212** [comment]
This issue has been solved by that issue. The `new_state` is not `new_states`. If anyone has problem, please check the following issue.
https://github.com/nuric/deeplogic/issues/14
